### ISSUE TITLE
How to install on DM500+ ?

### ISSUE THREAD

**Issue by armaghanshahzad** [jmendeth/dm500-satip#2]
Dm500+ uses NFI image file. I tried to install the image provided here but did not work. Can you please provide NFI image for DM500+?

**Comment by mildsunrise** [comment]
I find it very unlikely that my image will work on a DM500+. Also, I have never used NFI images and don't know how to produce one.

Since the scope for this project is the DM500 exclusively, I'm closing this issue.
If you or someone develops an image for the DM500+ without substantial changes, I'll happily merge them and extend the scope.
