### ISSUE TITLE
signal issues

### ISSUE THREAD

**Issue by jjsjackson** [jmendeth/dm500-satip#7]
i have flashed the latest image to a dm500s, i can see the tuner in tvheadend server, have added the muxes, even tried adding muxes individually, but no matter what i scan only 3 transponders

i am aimed at 91W, i see no option on setting the lnb type, my setup is a NA standard LNB connected directly to dm500s

i do get some services, about 100 in total i can stream in vlc thses ones, so its partially working

thanks in advance

**Comment by robbieb43** [comment]
Hi 

I wonder if the issue is not so much the sat-ip software but TV headend.  I cannot recall seeing much circular polarisation on the common European satellites in recent times so may not be part of the auto scan options? (Hispasat used to be circ polarised in the Pre digital days I recall). If the transponders you are seeing are ones such as the ABC one, this might be a clue as this is Vertical.  It may be worth using VLC or similar to check the streams directly- for the circular polarisation TPs you would need to put in pol=l or pol=r.  More details in the spec: http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf on page 43.

Just a thought.


Rob

**Comment by jjsjackson** [comment]
I will look into your suggestion on a side note, the channels that are scanned and working are on TPs,  10964V 10994V 11024V when on lyngsat looking at this sat, i dont see those, i see the TPs as cirlular R/L the R/L do show in muxes in tvheadend, just fail to scan -- i know signal is good on line, worked in ird before, and works on another receiver one of the channels i can view is on TP 21, 12516 R  and it doesnt even show in the muxes list  i have tried adding muxes manually, scan still fails also, in the sat to ip server settings in tvheadend there is no option to set lnb type appreciate any help ---- On Fri, 24 Aug 2018 08:32:28 -0400 robbieb43 <notifications@github.com> wrote ---- Hi I wonder if the issue is not so much the sat-ip software but TV headend. I cannot recall seeing much circular polarisation on the common European satellites in recent times so may not be part of the auto scan options? (Hispasat used to be circ polarised in the Pre digital days I recall). If the transponders you are seeing are ones such as the ABC one, this might be a clue as this is Vertical. It may be worth using VLC or similar to check the streams directly- for the circular polarisation TPs you would need to put in pol=l or pol=r. More details in the spec: http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf on page 43. Just a thought. Rob — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jjsjackson** [comment]
changed from a single feed to a dpp44 feed, the dpp44 is supplied by a dptwin lnb

all is good
